
version: '3'
services:
  myapp:
    container_name: interview
    restart: always
    environment: 
      - PORT=${PORT}
      - MONGODB=${MONGODB}
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
  redis:
    container_name: redis
    image: 'redis/redis-stack-server'